- id: enciente_termo_morning
  alias: enciende_termo_morning
  trigger:
  - entity_id: binary_sensor.termo_start
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: input_number.slider_termo_time
      value: '60'
    data_template:
      entity_id: input_number.slider_termo_time
      value: 60
    service: input_number.set_value
- action:
  - data:
      message: "HASS starting"
    service: notify.bot_to_grcanosa
  alias: hass_startup
  condition: []
  id: 'hass_startup'
  trigger:
    - event: start
      platform: homeassistant
