homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # Location required to calculate the time the sun rises and sets
  latitude: 40.407606
  longitude: -3.6659379
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 657
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  customize: !include_dir_merge_named include/customized


http: !include include/httpconfig.yaml

mqtt: !include include/mqtt.yaml

device_tracker: !include include/device_tracker.yaml

group: !include_dir_merge_named include/grupos

zwave: !include include/zwave.yaml

automation: !include_dir_list include/automation

script: !include_dir_merge_named include/scripts

# Example configuration.yaml entry
sensor: !include include/sensors.yaml

input_slider: !include include/input_slider.yaml

zone:
  name: SEPSA
  latitude: 40.247742
  longitude: -3.709661
  radius: 200
  icon: mdi:worker


panel_iframe:
  music:
    title: "Music"
    url: 'http://192.168.1.98:6680/musicbox_webclient/index.html'

notify:
  - name: grcanosabot
    platform: telegram
    api_key: 299955644:AAEBQY-7kb0PkC4LOfpirIzKi71RGnDoIBw
    chat_id: 15111383


# Example configuration.yaml entry
media_player:
  - platform: vlc
    name: Altavoz
# arguments: '--alsa-audio-device=hw:1,0'

tts:
  platform: google
  language: es

# Enables the frontend
frontend:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

logger:
  default: info

# Track the sun
#sun:

# Weather Prediction
#sensor:
#  platform: yr

# Show links to resources in log and frontend
#introduction:

# input_boolean:
#   boolean1:
#     name: Auxiliary
#     initial: off
#     icon: mdi:car
#
# binary_sensor:
#   - platform: template
#     sensors:
#       aux_binary:
#         value_template: '{{ states.input_slider.termo_time.state | int > 0 }}'
#         friendly_name: 'Sensor Auxiliary'
