- platform: nmap_tracker
  hosts: 192.168.1.1/24
  home_interval: 15
  consider_home: 30
  track_new_devices: False
  interval_seconds: 30
- platform: owntracks
  max_gps_accuracy: 200
  waypoints: True
  waypoint_whitelist:
    - grcanosa
    - sara
