- platform: template
  sensors: 
    termo_start:
      value_template: '{{states("input_select.termo_start_time") == states("sensor.time")}}'
      friendly_name: 'Termo Start'
    termo_start2:
      value_template: '{{states("input_text.texttest") == states("sensor.time")}}'
      friendly_name: "TestName"