- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload
- platform: template
  sensors:
    sensortermo_time:
      value_template: '{{ states.input_slider.slider_termo_time.state }}'
      friendly_name: 'Termo (min)'
      unit_of_measurement: 'min'
